version: '3.4'

services:
  projetobase.api:
    image: ${DOCKER_REGISTRY-}projetobasepi
    container_name: ProjetoBase
    build:
      context: .
      dockerfile: ProjetoBase.Api/Dockerfile

  sqldb:
   image: mcr.microsoft.com/mssql/server:2022-latest
   container_name: sqldb
   environment:
    - SA_PASSWORD=Teste*123
    - ACCEPT_EULA=Y
   ports:
    - "1450:1433"